### PR TITLE
Data Fetching : custom hook useRequest to fetch data

### PR DESCRIPTION
**Pull request by rparthas**
This demonstrates an example of data fetching using custom hook useRequest. This fixes issue #1

### CODE REVIEW

**Comment by cinfinit** [comment]
is the complete PR , that you were earlier mentioning in the ticket ?

**Comment by rparthas** [comment]
Yes @cinfinit . I have added the routes and the documentation. Let me know after review

**Comment by cinfinit** [comment]
Sure

**Comment by cinfinit** [comment]
@rparthas , looks cool enough ,next time could also prettify the code as well ,  merging :)

**Pull request merged**
