### PR TITLE
Add one of the basic way to fetch data in react

### PR DESCRIPTION
**Pull request by nalin-programmer**

### CODE REVIEW

**Comment by nalin-programmer** [comment]
It's done, please merge it with main repo

**Comment by cinfinit** [comment]
@nalin-programmer Kindly once again check either CONTRIBUTING.md / README.md and make changes accordingly and add relevant commit message while committing

**Comment by cinfinit** [comment]
Hey @nalin-programmer  , are you working on this , or should i reassign to someone else ?

**Comment by nalin-programmer** [comment]
Sorry I was busy with other stuff, I couldn't do this task, you may reassign this to someone else.

**Comment by cinfinit** [comment]
Sure @nalin-programmer , no issues

**Pull request closed without merging**
